// create simple gematria object
export const simple = [
  { letter: "a", value: 1, text: "one" },
  { letter: "b", value: 2, text: "two" },
  { letter: "c", value: 3, text: "three" },
  { letter: "d", value: 4, text: "four" },
  { letter: "e", value: 5, text: "five" },
  { letter: "f", value: 6, text: "six" },
  { letter: "g", value: 7, text: "seven" },
  { letter: "h", value: 8, text: "eight" },
  { letter: "i", value: 9, text: "nine" },
  { letter: "j", value: 10, text: "ten" },
  { letter: "k", value: 11, text: "eleven" },
  { letter: "l", value: 12, text: "twelve" },
  { letter: "m", value: 13, text: "thirteen" },
  { letter: "n", value: 14, text: "fourteen" },
  { letter: "o", value: 15, text: "fifteen" },
  { letter: "p", value: 16, text: "sixteen" },
  { letter: "q", value: 17, text: "seventeen" },
  { letter: "r", value: 18, text: "eighteen" },
  { letter: "s", value: 19, text: "nineteen" },
  { letter: "t", value: 20, text: "twenty" },
  { letter: "u", value: 21, text: "twenty one" },
  { letter: "v", value: 22, text: "twenty two" },
  { letter: "w", value: 23, text: "twenty three" },
  { letter: "x", value: 24, text: "twenty four" },
  { letter: "y", value: 25, text: "twenty five" },
  { letter: "z", value: 26, text: "twenty six" },
];

// create english gematria object
export const english = [
  { letter: "a", value: 6, text: "six" },
  { letter: "b", value: 12, text: "twelve" },
  { letter: "c", value: 18, text: "eighteen" },
  { letter: "d", value: 24, text: "twenty four" },
  { letter: "e", value: 30, text: "thirty" },
  { letter: "f", value: 36, text: "thirty six" },
  { letter: "g", value: 42, text: "forty two" },
  { letter: "h", value: 48, text: "forty eight" },
  { letter: "i", value: 54, text: "fifty four" },
  { letter: "j", value: 60, text: "sixty" },
  { letter: "k", value: 66, text: "sixty six" },
  { letter: "l", value: 72, text: "seventy two" },
  { letter: "m", value: 78, text: "seventy eight" },
  { letter: "n", value: 84, text: "eighty four" },
  { letter: "o", value: 90, text: "ninety" },
  { letter: "p", value: 96, text: "ninety six" },
  { letter: "q", value: 102, text: "one hundred two" },
  { letter: "r", value: 108, text: "one hundred eight" },
  { letter: "s", value: 114, text: "one hundred fourteen" },
  { letter: "t", value: 120, text: "one hundred twenty" },
  { letter: "u", value: 126, text: "one hundred twenty six" },
  { letter: "v", value: 132, text: "one hundred thirty two" },
  { letter: "w", value: 138, text: "one hundred thirty eight" },
  { letter: "x", value: 144, text: "one hundred forty four" },
  { letter: "y", value: 150, text: "one hundred fifty" },
  { letter: "z", value: 156, text: "one hundred fifty six" },
];

// create hebrew gematria object
export const hebrew = [
  { letter: "a", value: 1, text: "one" },
  { letter: "b", value: 2, text: "two" },
  { letter: "c", value: 3, text: "three" },
  { letter: "d", value: 4, text: "four" },
  { letter: "e", value: 5, text: "five" },
  { letter: "f", value: 6, text: "six" },
  { letter: "g", value: 7, text: "seven" },
  { letter: "h", value: 8, text: "eight" },
  { letter: "i", value: 9, text: "nine" },
  { letter: "j", value: 600, text: "six hundred" },
  { letter: "k", value: 10, text: "ten" },
  { letter: "l", value: 20, text: "twenty" },
  { letter: "m", value: 30, text: "thirty" },
  { letter: "n", value: 40, text: "forty" },
  { letter: "o", value: 50, text: "fifty" },
  { letter: "p", value: 60, text: "sixty" },
  { letter: "q", value: 70, text: "seventy" },
  { letter: "r", value: 80, text: "eighty" },
  { letter: "s", value: 90, text: "ninety" },
  { letter: "t", value: 100, text: "one hundred" },
  { letter: "u", value: 200, text: "two hundred" },
  { letter: "v", value: 700, text: "seven hundred" },
  { letter: "w", value: 900, text: "nine hundred" },
  { letter: "x", value: 300, text: "three hundred" },
  { letter: "y", value: 400, text: "four hundred" },
  { letter: "z", value: 500, text: "five hundred" },
];
